# ---------------- docker-compose v.s. dockerfile -----------------
# refer: https://www.reddit.com/r/docker/comments/9vjm9a/projects_with_dockercompose_but_without_dockerfile/
# dockerfile: Only when need to create a custom container image from scratch
# docker-compse: deploy a container from an image(public images are in docker hub)


version: '3.7'

services:
  prometheus:
    image: prom/prometheus:v2.14.0
    ports:
      - 9090:9090
    networks:
      - internal

  pushgateway:
    image: prom/pushgateway:v1.0.0
    networks:
      - internal
    ports:
     - 9091:9091

volumes:
  prometheus_volume:
    external: false

networks:
  internal:
